#!/usr/bin/env python3
"""breakout_site.py — render the EARLY-DISCOVERY research site into breakout_site/.

Reads breakout_discover.json (the small/mid-cap pre-hype discovery sweep) and,
if present, breakout_ideas.json (the large-cap breakout mode). The index leads
with the Early Discovery section; one disc_<TICKER>.html page is written per
discovery. Self-contained static HTML (no server / no CDN), emails fine.

Run: python3 breakout_site.py
"""
from __future__ import annotations
import json, os, html

import breakout_discover as bd

OUT = "breakout_site"
IDEAS_FILE = "breakout_ideas.json"   # optional large-cap mode

CSS = """
:root{--bg:#0a0e14;--card:#121822;--ink:#e6edf3;--mut:#8b9bb0;--ac:#00e5ff;--gd:#39d98a;--am:#ffb454;--rd:#ff6b6b}
*{box-sizing:border-box}
body{margin:0;background:linear-gradient(180deg,#070a0f,#0a0e14);color:var(--ink);
font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:0 0 60px}
a{color:var(--ac);text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:1040px;margin:0 auto;padding:0 18px}
header{padding:30px 0 10px;border-bottom:1px solid #1c2735;margin-bottom:22px}
h1{font-size:26px;margin:0 0 4px;letter-spacing:.4px}
h1 .em{color:var(--ac)}
.sub{color:var(--mut);font-size:13px}
.disc{background:#10161f;border:1px solid #2a1a0a;border-left:3px solid var(--am);
padding:12px 14px;border-radius:8px;margin:16px 0;color:#ffd9a8;font-size:12.5px}
h2{font-size:15px;letter-spacing:2px;text-transform:uppercase;color:var(--mut);
margin:30px 0 12px;border-bottom:1px solid #1c2735;padding-bottom:6px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:14px}
.card{background:var(--card);border:1px solid #1c2735;border-radius:12px;padding:16px;
transition:.15s;position:relative;overflow:hidden}
.card:hover{border-color:#2c3b4f;transform:translateY(-2px)}
.tk{font-size:20px;font-weight:700}
.nm{color:var(--mut);font-size:12.5px;margin:2px 0 10px}
.row{display:flex;justify-content:space-between;font-size:13px;padding:3px 0;border-bottom:1px dashed #1a2330}
.row span:first-child{color:var(--mut)}
.tag{display:inline-block;font-size:10.5px;font-weight:700;letter-spacing:.6px;
padding:3px 8px;border-radius:20px;margin-right:6px}
.STRONG{background:rgba(57,217,138,.16);color:var(--gd)}
.MODERATE{background:rgba(255,180,84,.16);color:var(--am)}
.WEAK{background:rgba(139,155,176,.16);color:var(--mut)}
.EMERGING{background:rgba(0,229,255,.12);color:var(--ac)}
.SPECULATIVE_EARLY{background:rgba(255,107,107,.14);color:var(--rd)}
.th{font-size:13px;color:#cdd9e5;margin:10px 0}
.rk{font-size:12px;color:var(--rd);margin-top:8px}
.sg{font-size:12px;color:var(--gd)}
.news{font-size:12px;color:var(--mut);margin-top:8px}
.news b{color:#cdd9e5;font-weight:600}
.back{font-size:13px;color:var(--mut)}
ul{margin:6px 0;padding-left:18px}li{margin:2px 0}
footer{color:#566;font-size:11px;margin-top:40px;text-align:center}
"""


def esc(x):
    return html.escape(str(x)) if x is not None else ""


def fmt(x, suf="", pre=""):
    return f"{pre}{x}{suf}" if x is not None else "&mdash;"


def card(d, link=True):
    r = d.get("ratings") or {}
    tk = esc(d["ticker"])
    head = (f'<a href="disc_{tk}.html"><span class=tk>{tk}</span></a>' if link
            else f'<span class=tk>{tk}</span>')
    return f"""<div class=card>
<span class="tag {esc(d.get('early_fit'))}">{esc(d.get('early_fit'))}</span>
<span class="tag {esc(d.get('tier'))}">{esc(d.get('tier'))}</span>
<div style="margin-top:8px">{head}</div>
<div class=nm>{esc(d.get('name'))}</div>
<div class=row><span>Market cap</span><span>{fmt(d.get('market_cap_b'),'B','$')}</span></div>
<div class=row><span>Price</span><span>{fmt(d.get('price'),'','$')}</span></div>
<div class=row><span>52w range pos</span><span>{fmt(d.get('base_pos_pct'),'%')}</span></div>
<div class=row><span>Analysts</span><span>{fmt(d.get('n_analysts'))} ({esc(d.get('coverage'))})</span></div>
<div class=row><span>Ratings B/H/S</span><span>{fmt(r.get('buy'))}/{fmt(r.get('hold'))}/{fmt(r.get('sell'))}</span></div>
<div class=row><span>EPS surprise</span><span>{fmt(d.get('earnings_surprise_pct'),'%')}</span></div>
<div class=row><span>Cheap?</span><span>{'yes' if d.get('cheap') else 'no'}</span></div>
<div class=th>{esc(d.get('thesis'))}</div>
<div class=rk>&#9888; {esc(d.get('key_risk'))}</div>
</div>"""


def page(title, body):
    return (f"<!doctype html><html><head><meta charset=utf-8>"
            f"<meta name=viewport content='width=device-width,initial-scale=1'>"
            f"<title>{esc(title)}</title><style>{CSS}</style></head>"
            f"<body><div class=wrap>{body}</div>"
            f"<footer>Generated by breakout_site.py &middot; data via Bigdata.com "
            f"(https://bigdata.com) &middot; speculative research, not advice</footer></body></html>")


def detail_page(d):
    tk = esc(d["ticker"])
    sigs = "".join(f"<li>{esc(s)}</li>" for s in (d.get("early_signals") or []))
    news = "".join(
        f"<div class=news><b>{esc(n.get('headline'))}</b><br>"
        f"{esc(n.get('source'))} &middot; {esc(n.get('date'))} &middot; tone: {esc(n.get('tone'))}</div>"
        for n in (d.get("news") or []))
    body = f"""<header>
<a class=back href="index.html">&larr; back to discovery</a>
<h1 style="margin-top:10px">{tk} <span class=em>&middot;</span> {esc(d.get('name'))}</h1>
<div class=sub>
<span class="tag {esc(d.get('early_fit'))}">{esc(d.get('early_fit'))}</span>
<span class="tag {esc(d.get('tier'))}">{esc(d.get('tier'))}</span></div>
</header>
{card(d, link=False)}
<h2>Valuation</h2>
<div class=th>{esc(d.get('valuation'))} &middot; cheap vs growth: {'yes' if d.get('cheap') else 'no'}</div>
<div class=row><span>Revenue growth</span><span>{fmt(d.get('rev_growth_pct'),'%')}</span></div>
<div class=row><span>Forward EPS rising</span><span>{'yes' if d.get('eps_rising') else 'no/—'}</span></div>
<div class=row><span>Margin / ROE</span><span>{fmt(d.get('margin_pct'),'%')}</span></div>
<h2>Early signals</h2><ul>{sigs or '<li>&mdash;</li>'}</ul>
<h2>Thesis</h2><div class=th>{esc(d.get('thesis'))}</div>
<h2>Key risk</h2><div class=rk>&#9888; {esc(d.get('key_risk'))}</div>
<h2>Dated news</h2>{news or '<div class=news>&mdash;</div>'}"""
    return page(f"{tk} — early discovery", body)


def build():
    doc = bd.load()
    os.makedirs(OUT, exist_ok=True)
    rows = bd.ranked(doc)

    # per-name detail pages
    for d in rows:
        with open(os.path.join(OUT, f"disc_{d['ticker']}.html"), "w") as f:
            f.write(detail_page(d))

    n_strong = sum(1 for d in rows if d.get("early_fit") == "STRONG")
    cards = "".join(card(d) for d in rows) or "<p class=sub>No discoveries this run.</p>"

    # optional large-cap breakout mode
    ideas_html = ""
    if os.path.exists(IDEAS_FILE):
        try:
            ideas = json.load(open(IDEAS_FILE))
            items = ideas.get("ideas", ideas if isinstance(ideas, list) else [])
            if items:
                lis = "".join(
                    f"<div class=card><div class=tk>{esc(i.get('ticker'))}</div>"
                    f"<div class=nm>{esc(i.get('name',''))}</div>"
                    f"<div class=th>{esc(i.get('thesis',''))}</div></div>" for i in items)
                ideas_html = f"<h2>Large-cap breakout mode</h2><div class=grid>{lis}</div>"
        except Exception:
            ideas_html = ""

    body = f"""<header>
<h1>The <span class=em>Early Discovery</span> Scout</h1>
<div class=sub>{esc(doc.get('_asof'))} &middot; {esc(doc.get('_source'))}</div>
</header>
<div class=disc>{esc(doc.get('_disclaimer'))}</div>
<h2>Early Discovery &middot; {len(rows)} names ({n_strong} STRONG)</h2>
<div class=grid>{cards}</div>
{ideas_html}"""
    with open(os.path.join(OUT, "index.html"), "w") as f:
        f.write(page("Early Discovery Scout", body))
    print(f"[breakout_site] wrote {OUT}/index.html + {len(rows)} disc_*.html pages "
          f"({n_strong} STRONG, {len(rows)} total)")


if __name__ == "__main__":
    build()
